### ISSUE TITLE
Unexpected error when syntax value is not valid

### ISSUE THREAD

**Issue by jvolkening** [haje61/Kamelon#6]
Hello,

This project is working great for a quick need that I had, thank you. I did notice what looks like a minor bug if the `syntax` parameter does not specify a valid value, e.g. if the invalid value "Shell" is passed:
```perl
use Syntax::Kamelon;

my $kam = Syntax::Kamelon->new(
   syntax => 'Shell',
   formatter => ['ANSI'],
);
while (my $line = <STDIN>) {
    $kam->Parse($line);
}
print $kam->Format;
```
it throws:
```bash
Can't locate object method "Debug" via package "Syntax::Kamelon" at /home/<user>/perl5/lib/perl5/Syntax/Kamelon.pm line 574.
```
Of course, it is an error either way but I don't think this was intended. If the `syntax` is valid it is not an issue.

**Comment by haje61** [comment]
Thanks for letting me know.
Always nice to learn somebody uses my work!
I'll have it spit out something more useful in the next release.
